### ISSUE TITLE
Same timestamp is sent for every request

### ISSUE THREAD

**Issue by zackangelo** [ryanbrozo/spray-hawk#6]
Unless you create a new `RequestTransformer` instance for every outbound request, the same timestamp will be used because the `addHawkCredentials` method is curried and the `ts` parameter is in the first group (https://github.com/ryanbrozo/spray-hawk/blob/master/lib/src/main/scala/com/ryanbrozo/spray/hawk/HawkRequestBuilding.scala#L45).  

A simple solution might be to convert the `ts` parameter to a thunk (e.g., `ts: () => TimeStamp`) so that it's re-evaluated every request?

**Comment by ryanbrozo** [comment]
There is a [CurrentTimeProvider](https://github.com/ryanbrozo/spray-hawk/blob/master/lib/src/main/scala/com/ryanbrozo/spray/hawk/package.scala#L118) type defined which I plan to use here, but is not currently used yet. I'll push some changes soon so it will be used already
